name: Bug Report
description: "File a bug report."
title: "[BUG]: "
labels:
  - "type:bug"
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to help us diagnose the problem.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a short description of the issue."
      placeholder: "e.g., App crashes when opening a file"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "Select your operating system."
      options:
        - "Windows"
        - "Debuntu"
        - "Kodi specific distros"
        - "Mac"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: jellyfin_version
    attributes:
      label: "Jellyfin Server Version"
      description: "Select the Jellyfin server version."
      options:
        - "10.7"
        - "10.8"
        - "10.9"
        - "10.10"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: kodi_version
    attributes:
      label: "Kodi Version"
      description: "Select the Kodi version."
      options:
        - "19"
        - "20"
        - "21"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the issue."
      placeholder: "e.g., 1. Open app. 2. Click button."
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Provide any other relevant information."
      placeholder: "e.g., App behavior after crash."
      optional: true
