name: Enhancement request [for roku]
description: Suggest a modification to an existing feature
labels: enhancement

body:
  - type: textarea
    attributes:
      label: Problem Description
      description: Describe the issue you are experiencing or the gap you are trying to address.
      placeholder: I often encounter issues when...

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Provide a detailed description of what you would like to see implemented or changed.
      placeholder: Describe the feature or change in detail.

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Outline any other approaches you have thought about or explored to solve the problem.
      placeholder: Describe any alternative solutions or features.

  - type: textarea
    attributes:
      label: Additional Information
      description: Include any relevant details, resources, or screenshots that might help in understanding or implementing the request.
      placeholder: Add any additional context here.
