name: "Bug Report [test]"
description: "Report an issue with the software."
title: "[BUG] "
labels: ["type:bug", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information to help us diagnose the problem.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short description of the issue.
      placeholder: e.g., App crashes when opening a file

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "Select your operating system or specify another."
      options:
        - "Windows"
        - "Debuntu"
        - "Kodi specific distros"
        - "Other Linux"
        - "Mac"
        - "Xbox"
        - "Other"
    validations:
      required: true

  - type: input
    id: os_other
    attributes:
      label: "Other Operating System"
      description: "Specify your operating system if 'Other' was selected."
      placeholder: "e.g., Raspberry Pi OS"
    validations:
      required: false