name: "Bug Report [NEW]"
description: "Report an issue with the software."
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a short description of the issue."
      placeholder: "e.g., App crashes when opening a file"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the issue."
      placeholder: |
        e.g., 
        1. Open the app.
        2. Click on the file.
        3. The app crashes.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "Specify the operating system you are using."
      placeholder: "e.g., Ubuntu 20.04"
      
  - type: input
    id: jellyfin_server
    attributes:
      label: "Jellyfin Server Version"
      description: "Specify the version of the Jellyfin server you're using. If you're using an unstable build, please include the commit hash."
      placeholder: "e.g., 10.7 or 10.8"
      
  - type: input
    id: kodi_version
    attributes:
      label: "Kodi Version"
      description: "Specify the Kodi version you're using."
      placeholder: "e.g., 19.0"
      
  - type: dropdown
    id: addon_mode
    attributes:
      label: "Addon Mode"
      description: "Select how you're using the addon."
      options:
        - "Addon-mode"
        - "Direct-path mode ('native')"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please provide the logs in a code block to help with debugging."
      placeholder: "Paste your logs here..."
      render: "bash"
    validations:
      required: true

  - type: textarea
    id: server_logs
    attributes:
      label: "Server Logs"
      description: "Please provide the server logs in a code block."
      placeholder: "Paste your server logs here..."
      render: "bash"
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Provide any other relevant information."
      placeholder: "e.g., Additional context or setup details"
      optional: true
